### PR TITLE
Add ability to set PTY code

### PR DESCRIPTION
**Pull request by dkulp**

### CODE REVIEW

**Comment by thomastech** [comment]
Hi Dan -

Thanks for the submission, I appreciate it. I'm currently working on adding your two API requests (PTY, Carrier ON/OFF), plus some other things. I'll fold your code into my workspace and will release everything when I've completed the changes.

- Thomas

**Comment by dkulp** [comment]
Small mistake in the code:  RDS_PTY_CODE_DEF should be 0x9, not 0xA.   0xA is "Country".

**Comment by thomastech** [comment]
> Small mistake in the code: RDS_PTY_CODE_DEF should be 0x9, not 0xA. 0xA is "Country".

RDS_PTY_CODE_DEF errata has been noted. I will apply the correction.

**Comment by thomastech** [comment]
@dkulp 
Just a heads up. The PTY code format in your API function is hex formatted. This will be changed to decimal format in the release version. So be sure to update your host controller to use decimal (0-29) instead of hex values.

**Comment by thomastech** [comment]
@dkulp 
Just a heads up. The PTY code format in your API function is hex formatted. This will be changed to decimal format in the release version. So be sure to update your host controller to use decimal (0-29) instead of hex values.

**Comment by thomastech** [comment]
Added PTY feature to controller API.
{PR was manually applied to version 1.1.0 release, along with other improvements}

Thank you for the submission!

**Pull request closed without merging**
